title: Brian's Github Page
author: brtho
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is Brian's first Github Page used to test out the functionality.

# social links
twitter_username: testhandle
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
